version: "3.1"

services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  java-service:
    build: .
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: postgres
    ports:
      - 8080:8080
    depends_on:
      - "db"
    command:
      [
        "wait-for-it.sh",
        "db:5432",
        "--",
        "java",
        "-jar",
        "/app/graphql-demo-service.jar",
      ]
